### ISSUE TITLE
ASTAR Pathfinding Issue

### ISSUE THREAD

**Issue by monitosht** [hfaisal02/COMP602_ATLAS#3]
A common issue noticed with the A* Pathfinding package is that if enemies with the Seeker component follow the player for long enough, they start overlapping, making it hard to distinguish between one and many enemies chasing the player. 

The pro version of the package has a potential fix to this issue in the form of an exclusive feature. However, the cost to upgrade from the free version would be $100, which is a significant hit to our budget. A discussion regarding this issue will need to be held with the scrum master.

**Comment by hfaisal02** [comment]
After careful consideration, I believe it is not optimal to upgrade the package from the free version to the pro version. This is because I think to meet our main goal for Sprint 2, this feature holds no value as our goal consists of making the game functional. This could be something we can look into for Sprint 3 as we start refining our game's features based off User feedback.
